version: '3.9'
services:
  db:
    image: postgres:14.10-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
      POSTGRES_USER: postgres
    ports:
      - "${PORT_MAPPING}"
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql
        volume:
          nocopy: true
    networks:
      - localnet
  admin:
    image: dpage/pgadmin4:8.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "${PGADMIN_PORT_MAPPING}"
    networks:
      - localnet
volumes:
  data:
networks:
  localnet:
    driver: bridge
