version: '3.9'
services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_ROOT_PASSWORD}"
      POSTGRES_USER: postgres
    ports:
      - "${PORT_MAPPING}"
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql
        volume:
          nocopy: true
    networks:
      - localnet
volumes:
  data:
networks:
  localnet:
    driver: bridge
